[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fitz>=0.0.1.dev2",
    "pymupdf>=1.26.3",
    "pypdf2>=3.0.1",
    "reportlab>=4.4.2",
    "streamlit>=1.46.1",
]
